
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AST;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int LOW = 22;
  public static final int ELSE = 7;
  public static final int PLUS = 14;
  public static final int RBRACE = 20;
  public static final int OR = 17;
  public static final int THEN = 6;
  public static final int SEMI = 4;
  public static final int WHILE = 8;
  public static final int END = 11;
  public static final int RETURN = 10;
  public static final int IF = 5;
  public static final int LBRACE = 19;
  public static final int ID = 26;
  public static final int DO = 9;
  public static final int BOOLEAN = 25;
  public static final int TYPE = 23;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int HIGH = 21;
  public static final int ASSIGN = 3;
  public static final int EQ = 12;
  public static final int INTEGER = 24;
  public static final int LESSTHEN = 13;
  public static final int SKIP = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SKIP",
  "ASSIGN",
  "SEMI",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "RETURN",
  "END",
  "EQ",
  "LESSTHEN",
  "PLUS",
  "MINUS",
  "MULT",
  "OR",
  "AND",
  "LBRACE",
  "RBRACE",
  "HIGH",
  "LOW",
  "TYPE",
  "INTEGER",
  "BOOLEAN",
  "ID"
  };
}

